# Deploy Nuxt 3 ke GitHub Pages
name: Deploy Nuxt site to Pages

on:
  push:
    branches: ["main"]   # otomatis jalan kalau push ke branch main
  workflow_dispatch:     # bisa dijalankan manual dari tab Actions

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
          cache: npm

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build Nuxt site (generate static)
        run: npm run generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
